version: "3"

services:
  client:
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.coc.rule=Host(`coc.${DOMAIN?:err}`)
      - traefik.http.routers.coc.service=ks
      - traefik.http.services.coc.loadbalancer.server.port=80
    networks:
      - traefik_default
    restart: unless-stopped

networks:
  traefik_default:
    external: true


