version: "3"

services:
  client:
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cracked-or-cooked.rule=Host(`cracked-or-cooked.${DOMAIN?:err}`)"
      - "traefik.http.routers.cracked-or-cooked.service=cracked-or-cooked"
      - "traefik.http.services.cracked-or-cooked.loadbalancer.server.port=80"
    networks:
      - traefik_default
    restart: unless-stopped

networks:
  traefik_default:
    external: true


